<?php

namespace PortfolioBundle\Repository;

/**
 * ProjectCategoriesMmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectCategoriesMmRepository extends \Doctrine\ORM\EntityRepository
{
}
