<?php

namespace DevLogBundle\Repository;

/**
 * ArticleCategoriesMmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleCategoriesMmRepository extends \Doctrine\ORM\EntityRepository
{
}
