<?php

namespace DevLogBundle\Repository;

/**
 * ArticleKeyWordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleKeyWordRepository extends \Doctrine\ORM\EntityRepository
{
}
