<?php

namespace DevLogBundle\Repository;

/**
 * ArticleBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
