<?php

namespace DevLogBundle\Repository;

/**
 * ArticleKeywordMmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleKeywordMmRepository extends \Doctrine\ORM\EntityRepository
{
}
